version: '3.0'

services:
  mysql-docker-container:
    image: mysql:5.7
    container_name: mysql-docker-container
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=autostreet_lk_locations
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=test123
    ports:
      - 3307:3306
    volumes:
      - /data/mysql
    networks:
      - autostreet

  eureka-discovery-server:
    image: eureka-discovery-server:latest
    container_name: eureka-discovery-server
    ports:
      - 8761:8761
    networks:
      - autostreet

  location-service:
    image: location-service:latest
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
      - eureka-discovery-server
    ports:
      - 8081:8080
    volumes:
      - /data/app
    networks:
      - autostreet

networks:
  autostreet:
    driver: bridge